# Generated by Django 4.2.4 on 2023-09-01 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeLivraria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloLivro', models.CharField(max_length=100)),
                ('autorLivro', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('livraria', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.livraria')),
            ],
        ),
    ]
